package com.example.filebox

import javax.sql.DataSource

/**
 * Filebox schema
 *
 * Creates the plugin's own tables, one per datasource it declares. The declarations are
 * written to run on both database types the gateway offers a plugin rather than tailored
 * to the one each currently points at, which keeps them portable if a datasource is ever
 * re-pointed:
 *
 * - identifiers are generated by the plugin, not by the database, because
 *   `auto_increment` and `autoincrement` are not the same thing;
 * - times are epoch milliseconds, because MySQL and SQLite do not accept the same
 *   datetime literal;
 * - every statement is `create table if not exists`, and no index is created, because
 *   MySQL has no `create index if not exists` and SQLite has no inline `key` clause.
 *
 * @author FatttSnake, fatttsnake@gmail.com
 * @since 1.0.0
 */
object FileboxSchema {
    /**
     * Files the plugin stored, one row per location-addressed object
     */
    private const val CREATE_FILE_TABLE = """
        create table if not exists t_p_filebox_file
        (
            id          varchar(36)  not null primary key,
            owner_id    bigint       not null,
            name        varchar(255) not null,
            size        bigint       not null,
            path        varchar(512) not null,
            create_time bigint       not null
        )
    """

    /**
     * Snapshots the plugin stored, keyed by content so identical text shares one row
     */
    private const val CREATE_SNAPSHOT_TABLE = """
        create table if not exists t_p_filebox_snapshot
        (
            content_key varchar(64) not null primary key,
            owner_id    bigint      not null,
            size        bigint      not null,
            create_time bigint      not null
        )
    """

    /**
     * Drop the file table
     */
    private const val DROP_FILE_TABLE = "drop table if exists t_p_filebox_file"

    /**
     * Drop the snapshot table
     */
    private const val DROP_SNAPSHOT_TABLE = "drop table if exists t_p_filebox_snapshot"

    /**
     * Create the file table when it is missing
     *
     * Called on every start, which is what makes a datasource that was configured after the
     * plugin was installed work: the gateway remounts the plugin for it, and this runs again
     * on the way up.
     *
     * A failure is allowed to propagate - it fails the mount and lands in the plugin's
     * `load_error`, which is more useful to an administrator than a plugin that comes up
     * pretending to work and then fails on every call.
     *
     * @param dataSource The plugin's file datasource, or null while it is unconfigured
     * @author FatttSnake, fatttsnake@gmail.com
     * @since 1.0.0
     * @see DataSource
     */
    fun ensureFiles(dataSource: DataSource?) = dataSource?.let { execute(it, CREATE_FILE_TABLE) }

    /**
     * Create the snapshot table when it is missing
     *
     * @param dataSource The plugin's cache datasource, or null when the gateway supplied none
     * @author FatttSnake, fatttsnake@gmail.com
     * @since 1.0.0
     * @see ensureFiles
     */
    fun ensureSnapshots(dataSource: DataSource?) = dataSource?.let { execute(it, CREATE_SNAPSHOT_TABLE) }

    /**
     * Drop what this plugin created, on an uninstall that asked for its data to be deleted
     *
     * A datasource that is absent - an unconfigured one - has nothing this plugin put there,
     * so there is nothing to drop in it.
     *
     * @param files The plugin's file datasource, or null while it is unconfigured
     * @param snapshots The plugin's snapshot datasource, or null when the gateway supplied none
     * @author FatttSnake, fatttsnake@gmail.com
     * @since 1.0.0
     * @see DataSource
     */
    fun dropAll(files: DataSource?, snapshots: DataSource?) {
        files?.let { execute(it, DROP_FILE_TABLE) }
        snapshots?.let { execute(it, DROP_SNAPSHOT_TABLE) }
    }

    /**
     * Run one statement on a datasource
     */
    private fun execute(dataSource: DataSource, ddl: String) {
        dataSource.connection.use { connection ->
            connection.createStatement().use { statement ->
                statement.executeUpdate(ddl)
            }
        }
    }
}
